spring.application.name=invernadero
# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/logicwave
spring.datasource.username=postgres
spring.datasource.password=emma132521

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
# Mantiene el esquema existente y solo aplica cambios estructurales sin recrear la base en cada arranque.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN DEL SERVIDOR WEB
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACIÓN MQTT (MOSQUITTO)
# ==========================================
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=invernadero-server
# El símbolo '#' es un comodín. Escuchará todo lo que empiece con "invernadero/sensores/"
mqtt.topic.sensores=invernadero/+/sensores

jwt.secret=InvernaderoSecretKeySuperSegura1234567890ParaSpringSecurity
jwt.expiration=86400000 
# (El token durará 24 horas = 86400000 ms)